import ROOT
import argparse

ROOT.gROOT.SetBatch(True)

parser = argparse.ArgumentParser()
parser.add_argument('-i','--input',type=str, required = True)
args= parser.parse_args()

ifile = args.input
if ifile == 'test':
	f1 = ROOT.TFile("../Firefighter/washAOD/output/output_Mchi-60_dMchi-20_100mm.root")
	ofile = "output_test.pdf"
	t1 = f1.Get("TRIG_dsa2/trigEffiForMetTrack")
	t2 = f1.Get("TRIG_dsa2/trigEffiForMetTrackFired")
else:
	ofile = "output/trigeff_%smm.pdf"%ifile
	f1 = ROOT.TFile("../Firefighter/washAOD/output/output_%smm.root"%ifile)
	t1 = f1.Get("TRIG_dsa2/trigEffiForMetTrack")
	t2 = f1.Get("TRIG_dsa2/trigEffiForMetTrackFired")
hist_sel_met = ROOT.TH1F("histselmet","Met",100,0,300)
hist_sel_jetpt = ROOT.TH1F("histseljetpt","leading jet pt",100,0,500)
hist_sel_jeteta = ROOT.TH1F("histseljeteta","leading jet eta",20,-6,6)
hist_sel_jetphi = ROOT.TH1F("histseljetphi","leading jet phi",20,-6,6)
hist_sel_mupt = ROOT.TH1F("histselmupt","leading mu pt",50,0,150)
hist_sel_mueta = ROOT.TH1F("histselmueta","leading mu eta",20,-6,6)
hist_sel_muphi = ROOT.TH1F("histselmuphi","leading mu phi",20,-6,6)
hist_sel_met.Sumw2() 
hist_sel_jetpt.Sumw2() 
hist_sel_jeteta.Sumw2() 
hist_sel_jetphi.Sumw2() 
hist_sel_mupt.Sumw2() 
hist_sel_mueta.Sumw2() 
hist_sel_muphi.Sumw2() 
hist_sel_met.GetXaxis().SetTitle("MET [GeV]") 
hist_sel_met.GetYaxis().SetTitle("Counts") 
hist_sel_jetpt.GetXaxis().SetTitle("pt [GeV]") 
hist_sel_jetpt.GetYaxis().SetTitle("Counts") 
hist_sel_jeteta.GetXaxis().SetTitle("eta")
hist_sel_jeteta.GetYaxis().SetTitle("Counts") 
hist_sel_jetphi.GetXaxis().SetTitle("phi")
hist_sel_jetphi.GetYaxis().SetTitle("Counts") 
hist_sel_mupt.GetXaxis().SetTitle("pt [GEV]")
hist_sel_mupt.GetYaxis().SetTitle("Counts") 
hist_sel_mueta.GetXaxis().SetTitle("eta")
hist_sel_mueta.GetYaxis().SetTitle("Counts") 
hist_sel_muphi.GetXaxis().SetTitle("phi")
hist_sel_muphi.GetYaxis().SetTitle("Counts") 
for entry in t1:
	met =entry.met_met
	jetpt =entry.jet1_pt
	jeteta =entry.jet1_eta
	jetphi =entry.jet1_phi
	mupt =entry.mu1_pt
	mueta =entry.mu1_eta
	muphi =entry.mu1_phi
	hist_sel_met.Fill(met)
	hist_sel_jetpt.Fill(jetpt)
	hist_sel_jeteta.Fill(jeteta)
	hist_sel_jetphi.Fill(jetphi)
	hist_sel_mupt.Fill(mupt)
	hist_sel_mueta.Fill(mueta)
	hist_sel_muphi.Fill(muphi)
hist_fired_met =   ROOT.TH1F("histfiredmet","(triggered) Met",100,0,300)
hist_fired_jetpt = ROOT.TH1F("histfiredjetpt","(triggered) leading jet pt",100,0,500)
hist_fired_jeteta =ROOT.TH1F("histfiredjeteta","(triggered) leading jet eta",20,-6,6)
hist_fired_jetphi =ROOT.TH1F("histfiredjetphi","(triggered) leading jet phi",20,-6,6)
hist_fired_mupt =  ROOT.TH1F("histfiredmupt","(triggered) leading mu pt",50,0,150)
hist_fired_mueta = ROOT.TH1F("histfiredmueta","(triggered) leading mu eta",20,-6,6)
hist_fired_muphi = ROOT.TH1F("histfiredmuphi","(triggered) leading mu phi",20,-6,6)
hist_fired_met.Sumw2() 
hist_fired_jetpt.Sumw2() 
hist_fired_jeteta.Sumw2() 
hist_fired_jetphi.Sumw2() 
hist_fired_mupt.Sumw2() 
hist_fired_mueta.Sumw2() 
hist_fired_muphi.Sumw2() 
hist_fired_met.GetXaxis().SetTitle("MET [GeV]") 
hist_fired_met.GetYaxis().SetTitle("Counts") 
hist_fired_jetpt.GetXaxis().SetTitle("pt [GeV]") 
hist_fired_jetpt.GetYaxis().SetTitle("Counts") 
hist_fired_jeteta.GetXaxis().SetTitle("eta")
hist_fired_jeteta.GetYaxis().SetTitle("Counts") 
hist_fired_jetphi.GetXaxis().SetTitle("phi")
hist_fired_jetphi.GetYaxis().SetTitle("Counts") 
hist_fired_mupt.GetXaxis().SetTitle("pt [GEV]")
hist_fired_mupt.GetYaxis().SetTitle("Counts") 
hist_fired_mueta.GetXaxis().SetTitle("eta")
hist_fired_mueta.GetYaxis().SetTitle("Counts") 
hist_fired_muphi.GetXaxis().SetTitle("phi")
hist_fired_muphi.GetYaxis().SetTitle("Counts") 
for entry in t2:
	met =entry.met_met
	jetpt =entry.jet1_pt
	jeteta =entry.jet1_eta
	jetphi =entry.jet1_phi
	mupt =entry.mu1_pt
	mueta =entry.mu1_eta
	muphi =entry.mu1_phi
	hist_fired_met.Fill(met)
	hist_fired_jetpt.Fill(jetpt)
	hist_fired_jeteta.Fill(jeteta)
	hist_fired_jetphi.Fill(jetphi)
	hist_fired_mupt.Fill(mupt)
	hist_fired_mueta.Fill(mueta)
	hist_fired_muphi.Fill(muphi)
hist_eff_met =   hist_fired_met.Clone("histeffmet")
hist_eff_met.Divide(hist_sel_met) 
hist_eff_met.SetMaximum(1.0) 
hist_eff_met.SetMinimum(0.0) 
hist_eff_jetpt = hist_fired_jetpt.Clone("histeffjetpt")
hist_eff_jetpt.Divide(hist_sel_jetpt) 
hist_eff_jetpt.SetMaximum(1.0) 
hist_eff_jetpt.SetMinimum(0.0) 
hist_eff_jeteta =hist_fired_jeteta.Clone("histeffjeteta")
hist_eff_jeteta.Divide(hist_sel_jeteta) 
#hist_eff_jeteta.SetMaximum(1.0) 
hist_eff_jeteta.SetMinimum(0.0) 
hist_eff_jetphi =hist_fired_jetphi.Clone("histeffjetphi")
hist_eff_jetphi.Divide(hist_sel_jetphi) 
#hist_eff_jetphi.SetMaximum(1.0) 
hist_eff_jetphi.SetMinimum(0.0) 
hist_eff_mupt =  hist_fired_mupt.Clone("histeffmupt")
hist_eff_mupt.Divide(hist_sel_mupt)
hist_eff_mupt.SetMaximum(0.5) 
hist_eff_mupt.SetMinimum(0.0) 
hist_eff_mueta = hist_fired_mueta.Clone("histeffmueta")
hist_eff_mueta.Divide(hist_sel_mueta) 
#hist_eff_mueta.SetMaximum(1.0) 
hist_eff_mueta.SetMinimum(0.0) 
hist_eff_muphi = hist_fired_muphi.Clone("histeffmuphi")
hist_eff_muphi.Divide(hist_sel_muphi) 
#hist_eff_muphi.SetMaximum(1.0) 
hist_eff_muphi.SetMinimum(0.0) 
hist_eff_met.GetXaxis().SetTitle("MET [GeV]") 
hist_eff_met.GetYaxis().SetTitle("efficiency") 
hist_eff_jetpt.GetXaxis().SetTitle("pt [GeV]") 
hist_eff_jetpt.GetYaxis().SetTitle("efficiency") 
hist_eff_jeteta.GetXaxis().SetTitle("eta")
hist_eff_jeteta.GetYaxis().SetTitle("efficiency") 
hist_eff_jetphi.GetXaxis().SetTitle("phi")
hist_eff_jetphi.GetYaxis().SetTitle("efficiency") 
hist_eff_mupt.GetXaxis().SetTitle("pt [GEV]")
hist_eff_mupt.GetYaxis().SetTitle("efficiency") 
hist_eff_mueta.GetXaxis().SetTitle("eta")
hist_eff_mueta.GetYaxis().SetTitle("efficiency") 
hist_eff_muphi.GetXaxis().SetTitle("phi")
hist_eff_muphi.GetYaxis().SetTitle("efficiency") 
hist_eff_met.SetTitle("Met")
hist_eff_jetpt.SetTitle("leading jet pt")
hist_eff_jeteta.SetTitle("leading jet eta")
hist_eff_jetphi.SetTitle("leading jet phi")
hist_eff_mupt.SetTitle("leading mu pt")
hist_eff_mueta.SetTitle("leading mu eta")
hist_eff_muphi.SetTitle("leading mu phi")

erf_met = ROOT.TF1("erf_met","TMath::Erf((x-100-[0])*[1])*1",50,170) 
erf_met.SetParameters(0.5,2.0)

pp = ROOT.TCanvas("pp","pp",800,800)
pp.SetLogy(0)
hist_eff_met.Fit("erf_met")
hist_eff_met.Draw("E1")
pp.Print(ofile+"(")
pp.Clear()
hist_eff_jetpt.Draw("E1")
pp.Print(ofile)
pp.Clear()
hist_eff_jeteta.Draw("E1")
pp.Print(ofile)
pp.Clear()
hist_eff_jetphi.Draw("E1")
pp.Print(ofile)
hist_eff_mupt.Draw("E1")
pp.Print(ofile)
pp.Clear()
hist_eff_mueta.Draw("E1")
pp.Print(ofile)
pp.Clear()
hist_eff_muphi.Draw("E1")
pp.Print(ofile)
pp.Clear()
pp.SetLogy(1)
hist_sel_met.Draw()
pp.Print(ofile)
pp.Clear()
hist_sel_jetpt.Draw()
pp.Print(ofile)
pp.Clear()
hist_sel_jeteta.Draw()
pp.Print(ofile)
pp.Clear()
hist_sel_jetphi.Draw()
pp.Print(ofile)
hist_sel_mupt.Draw()
pp.Print(ofile)
pp.Clear()
hist_sel_mueta.Draw()
pp.Print(ofile)
pp.Clear()
hist_sel_muphi.Draw()
pp.Print(ofile)
pp.Clear()
hist_fired_met.Draw()
pp.Print(ofile)
pp.Clear()
hist_fired_jetpt.Draw()
pp.Print(ofile)
pp.Clear()
hist_fired_jeteta.Draw()
pp.Print(ofile)
pp.Clear()
hist_fired_jetphi.Draw()
pp.Print(ofile)
hist_fired_mupt.Draw()
pp.Print(ofile)
pp.Clear()
hist_fired_mueta.Draw()
pp.Print(ofile)
pp.Clear()
hist_fired_muphi.Draw()
pp.Print(ofile+")")
del pp
